---
- name: Create AP wireless profile
  cisco.meraki.networks_camera_wireless_profiles:
    meraki_api_key: "{{ meraki_key }}"
    state: present
    name: Demo-RF-Profile
    networkId: string
    ssid:
      authMode: 8021x-radius
      encryptionMode: wpa-eap
      name: ssid test
