---
- name: Attach Port to Port Scheduler

  hosts: localhost
  vars:
    meraki_api_key: "{{ meraki_key }}"
    org_name: "{{ org_name }}"
  
  tasks:
    - name: Get Organization Networks
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result
      
    - name: Filter networks with "wireless" productTypes
      set_fact:
        filtered_networks: "{{ result.meraki_response | selectattr('productTypes', 'contains', 'wireless') | list }}"
      register: network_id_get
  
    - name: Attach Port Schedule
      cisco.meraki.devices_switch_ports:
        meraki_api_key: "{{ meraki_key }}"
        enabled: true
        isolationEnabled: false
        allowedVlans: 1,3,5-10
        linkNegotiation: Auto negotiate
        poeEnabled: true
        state: present
        portScheduleId: "Weekdays schedule"
        rstpEnabled: true
        stormControlEnabled: true
        stpGuard: disabled
        type: access
        vlan: 10
        voiceVlan: 20
