---
- name: meraki deployment
  hosts: localhost
  vars:
    meraki_api_key: "{{ meraki_key }}"
    org_name: "Red Hat"

  tasks:

    - name: include variables for devices
      include_vars:
        file: devices.yaml
        name: devices

    - name: include variables for addresses
      include_vars:
        file: addresses.yaml
        name: addresses

    - name: Create site network
      cisco.meraki.networks:
        meraki_api_key: "{{ meraki_api_key }}"
        state: present
        name: "Branch-Oren"
        organizationId: "Red Hat"
        productTypes:
          - switch
          - appliance
          - wireless
