---
- hosts: localhost
  
  tasks:
    - name: Get Organization Networks
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result
      
    - name: Filter networks with "wireless" productTypes
      set_fact:
        filtered_networks: "{{ result.meraki_response | selectattr('productTypes', 'contains', 'appliance') | list }}"
      register: network_id_get
      
    - name: Update by id
      cisco.meraki.networks_appliance_firewall_firewalled_services:
        meraki_api_key: "{{ meraki_key }}"
        state: present
        access: restricted
        allowedIps:
        - 10.123.123.10
        networkId: "{{ filtered_networks.0.id }}"
        service: ICMP
