---
- hosts: localhost

  vars:
   meraki_key: "{{ meraki_key }}"
   org_id: "{{ org_id }}"
   network_name: "{{ network_name }}"

  tasks:
    - name: Get Organization Networks
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result
      
    - name: Get network_id
      set_fact:
        network_id: "{{ item.id }}"
      when: item.name == network_name
      loop: "{{ result.meraki_response }}"
    

