---
Net_Name: hostvars['localhost']['off_network.results.0.meraki_response.id']
meraki_api_key: "{{ meraki_key }}"
org_name: "{{ orgname }}"

SSID:
  - debug:
    var: hostvars['localhost']['off_network.results.0.meraki_response.id']
  - name: MyCompany_employees
    number: 1
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: 4nsibl3Employees!
      wpa_encryption_mode: WPA2 only
    vlan:
      useVlanTagging: true
      defaultVlanId: 100
    ipAssignmentMode: Bridge mode
    lanIsolationEnabled: true
    
  - name: MyCompany_customers
    number: 2
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: Ansible.2022
      wpa_encryption_mode: WPA2 only
    state: present
    visible: true
    availableOnAllAps: true
    vlan:
      useVlanTagging: true
      defaultVlanId: 200
    ipAssignmentMode: Bridge mode
    lanIsolationEnabled: true
    
  - name: MyCompany_contractors
    number: 3
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: Ansible.2022
      wpa_encryption_mode: WPA2 only
    vlan:
      useVlanTagging: true
      defaultVlanId: 300
    state: present
    ipAssignmentMode: Bridge mode
    lanIsolationEnabled: false
    
  - name: MyCompany_cameras
    number: 4
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: Ansible.2022
      wpa_encryption_mode: WPA2 only
    vlan:
      useVlanTagging: true
      defaultVlanId: 400
    ipAssignmentMode: Bridge mode
    lanIsolationEnabled: false
    state: present
