---
Net_Name: "{{ net_name }}"
meraki_api_key: "{{ meraki_key }}"
org_name: "{{ orgname }}"

SSID:
    
  - name: MyCompany_employees
    number: 1
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: 4nsibl3Employees!
      wpa_encryption_mode: WPA2 only
    vlan:
      useVlanTagging: true
      defaultVlanId: 100
    
  - name: MyCompany_customers
    number: 2
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: Ansible.2022
      wpa_encryption_mode: WPA2 only
    state: present
    visible: true
    availableOnAllAps: true
    vlan:
      useVlanTagging: true
      defaultVlanId: 200
    ipAssignmentMode: Bridge mode
    lanIsolationEnabled: true
    splashPage: None
    
  - name: MyCompany_contractors
    number: 3
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: Ansible.2022
      wpa_encryption_mode: WPA2 only
    vlan:
      useVlanTagging: true
      defaultVlanId: 300
    state: present
    
  - name: MyCompany_cameras
    number: 4
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: Ansible.2022
      wpa_encryption_mode: WPA2 only
    vlan:
      useVlanTagging: true
      defaultVlanId: 400
    state: present
