---
- hosts: localhost

  vars_files:
    - meraki_wifi_vars.yml
  
  tasks:
    - name: Edit SSID Settings
      cisco.meraki.networks_wireless_ssids: 
        meraki_api_key: "{{ meraki_key }}"
        networkId: "{{ Net_Name }}"
        enabled: "{{ item.enabled }}"
        state: "{{ item.state | default('present') }}"
        name: "{{ item.name }}"
        number: "{{ item.number }}"
        encryptionMode: "{{ item.encryption_mode }}"
        authMode: "{{ item[2].auth_mode }}"
        psk: "{{ item.psk }}"
        wpaEncryptionMode: "{{ item.wpa_encryption_mode }}"
        visible: "{{ item.visible | default('true')  }}"
        availableOnAllAps: "{{ item.availableOnAllAps | default('false')  }}"
        useVlanTagging: "{{ item.useVlanTagging | default('false')  }}"
        defaultVlanId: "{{ item.defaultVlanId }}"
        ipAssignmentMode: "{{ item.ipAssignmentMode }}"
        lanIsolationEnabled: true
        splashPage: "{{ item.splashPage }}"
      delegate_to: localhost
      loop: "{{ SSID }}"
