---
- hosts: localhost

  vars_files:
    - meraki_wifi_vars.yml
  
  tasks:
  - debug:
      var: "Net_Id"
      
    - name: Edit SSID Settings
      cisco.meraki.networks_wireless_ssids: 
        meraki_api_key: "{{ meraki_key }}"
        networkId: "{{ Net_Name }}"
        enabled: "{{ item.enabled }}"
        state: "{{ item.state | default('present') }}"
        name: "{{ item.name }}"
        number: "{{ item.number }}"
        encryptionMode: "{{ item.authentication.encryption_mode }}"
        authMode: "{{ item.authentication.auth_mode }}"
        psk: "{{ item.authentication.psk }}"
        wpaEncryptionMode: "{{ item.authentication.wpa_encryption_mode }}"
        visible: "{{ item.visible | default('true')  }}"
        availableOnAllAps: "{{ item.availableOnAllAps | default('false')  }}"
        useVlanTagging: "{{ item.vlan.useVlanTagging | default('false')  }}"
        defaultVlanId: "{{ item.vlan.defaultVlanId }}"
        ipAssignmentMode: "{{ item.ipAssignmentMode }}"
        lanIsolationEnabled: true
      delegate_to: localhost
      loop: "{{ SSID }}"
