---
meraki_api_key: "{{ meraki_key }}"
org_name: "{{ orgname }}"
org_id: "{{ org_id }}"

SSID:
  - name: MyCompany_employees
    number: 2
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: 4nsibl3Employees!
      wpa_encryption_mode: WPA2 only
    vlan:
      use_vlan_tagging: true
      defaultVlanId: 100
    visible: false
    availableOnAllAps: true
    
  - name: MyCompany_customers
    number: 3
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: Ansible.2022
      wpa_encryption_mode: WPA2 only
    state: present
    visible: true
    availableOnAllAps: true
    vlan:
      useVlanTagging: true
      defaultVlanId: 200
    visible: true
    availableOnAllAps: true
    
  - name: MyCompany_contractors
    number: 4
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: Ansible.2022
      wpa_encryption_mode: WPA2 only
    vlan:
      useVlanTagging: true
      defaultVlanId: 300
    state: present
    visible: false
    availableOnAllAps: true
    
  - name: MyCompany_cameras
    number: 5
    enabled: true
    authentication:
      auth_mode: psk
      encryption_mode: wpa
      psk: Ansible.2022
      wpa_encryption_mode: WPA2 only
    vlan:
      useVlanTagging: true
      defaultVlanId: 400
    state: present
    visible: false
    availableOnAllAps: true
